export type * from './Signup'
export type * from './Auth'
export type * from './Settings'
export type * from './Notifications'
export type * from './Modals'
export type * from './School'
export type * from './Lessons'
export type * from './AcademicPaper'
