export type * from './Signup'
export type * from './Auth'
export type * from './Settings'
export type * from './Students'
export type * from './Notifications'
export type * from './Teachers'
export type * from './Modals'
