export { AcademicPaperView } from './AcademicPaperView'
export { Comments } from './Comments'
export { Header } from './Header'
export { CardSource } from './CardSources'
export { AvaliationModal } from './AvaliationModal'
