import type { ReactNode } from 'react'
import './globals.css'
import { LayoutProvider } from '@/providers'
import { Roboto } from 'next/font/google'
import 'react-toastify/dist/ReactToastify.css'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
})
export const metadata = {
  title: 'School Guardian',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  )
}
