export type * from './school-service-props'
export type * from './auth-service-props'
export type * from './student-service-props'
export type * from './teacher-service-props'
export type * from './course-service-props'
export type * from './semester-service-props'
export type * from './lesson-service-props'
export type * from './class-service-props'
